title: Feahnthor
email: test@gmail.com
description: A collection of projects by Henry F.
baseurl: ""
url: "https://feahnthor.github.io"
github:
  zip_url: http://example.com/download.zip
  another_url: another value
show_downloads: ["true"]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

